# Generated by Django 4.2.1 on 2023-06-23 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lockwell_208_land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtb_matrix',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)screate', to=settings.AUTH_USER_MODEL),
        ),
    ]
