# Generated by Django 4.2.1 on 2023-06-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0003_mineralandia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineralandia',
            name='numero',
        ),
        migrations.AddField(
            model_name='mineralandia',
            name='nome',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mineralandiafornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oneTokey', to='relacionChip.telefone', unique=True)),
            ],
        ),
    ]
