# Generated by Django 4.2.1 on 2023-06-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0006_alter_mineralandia_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineralandia',
            old_name='Telefone',
            new_name='telefone',
        ),
    ]
