# Generated by Django 4.2.1 on 2023-06-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0007_rename_telefone_mineralandia_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineralandia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cliente', to='relacionChip.cliente'),
        ),
        migrations.AlterField(
            model_name='mineralandia',
            name='telefone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Telefone', to='relacionChip.telefone'),
        ),
    ]
