# Generated by Django 4.2.1 on 2023-06-27 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0008_alter_mineralandia_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineralandia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relacionChip.cliente'),
        ),
        migrations.AlterField(
            model_name='mineralandia',
            name='telefone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relacionChip.telefone'),
        ),
    ]
