# Generated by Django 4.2.1 on 2023-06-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0009_alter_mineralandia_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='relacionChip.cliente'),
        ),
    ]
