# Generated by Django 4.2.1 on 2023-06-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0010_alter_telefone_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacionChip.cliente'),
        ),
    ]
