# Generated by Django 4.2.1 on 2023-07-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0012_city_district_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
