# Generated by Django 4.2.1 on 2023-07-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0014_alter_district_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persona',
        ),
    ]
