# Generated by Django 4.2.1 on 2023-07-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0015_rename_person_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='uf',
            field=models.CharField(choices=[('MG', 'Minas Gerais'), ('SP', 'São paulo'), ('RJ', 'Rio de Janeiros'), ('ES', 'Espirito Santo')], max_length=2, verbose_name='UF'),
        ),
    ]
