# Generated by Django 4.2.1 on 2023-07-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0016_alter_city_uf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',), 'verbose_name': 'bairro', 'verbose_name_plural': 'bairros'},
        ),
    ]
