# Generated by Django 4.2.1 on 2023-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0017_alter_district_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='exist_address',
            field=models.BooleanField(default=False, help_text='Se for True o item ativo em uso . Se for False o item está inativo.', verbose_name='em uso /inativo'),
        ),
    ]
