# Generated by Django 4.2.1 on 2023-08-18 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relacionChip', '0018_persona_exist_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='relMarketingAddSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Avaliando'), ('4', 'Analise'), ('5', 'Paralizado'), ('6', 'Pendente'), ('7', 'Negado')], default=2, max_length=20, null=True)),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='privilegio')),
                ('relsupplier_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineralandiafornecedor', to='relacionChip.mineralandiafornecedor', verbose_name='mineslandia')),
            ],
            options={
                'verbose_name': 'relmercado_map',
                'verbose_name_plural': 'marketingaddsuppliers',
                'ordering': ('relsupplier_market',),
            },
        ),
    ]
