# Generated by Django 4.2.1 on 2023-08-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_alter_supplier_options_relchipsupplier'),
        ('relacionChip', '0019_relmarketingaddsuppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relmarketingaddsuppliers',
            name='relsupplier_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to='supplier.relchipsupplier', verbose_name='supplier-adv'),
        ),
    ]
