# Generated by Django 4.2.1 on 2023-08-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0011_alter_supplier_options'),
        ('relacionChip', '0020_alter_relmarketingaddsuppliers_relsupplier_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relmarketingaddsuppliers',
            name='relsupplier_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to='supplier.supplier', verbose_name='supplier-adv'),
        ),
    ]
