# Generated by Django 4.2.1 on 2023-08-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0021_alter_relmarketingaddsuppliers_relsupplier_market'),
    ]

    operations = [
        migrations.DeleteModel(
            name='relMarketingAddSuppliers',
        ),
    ]
