# Generated by Django 4.2.1 on 2023-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_ca_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
