# Generated by Django 4.2.1 on 2023-06-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_ca_novo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='novo',
        ),
    ]
