# Generated by Django 4.2.1 on 2023-06-01 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_paymentmethod_alter_ca_options_alter_ca_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='PrivilegesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
