# Generated by Django 4.2.1 on 2023-06-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_paymentrequirements_privilegesaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegesaccount',
            name='account',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='conta'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkaccounts', to='finance.ca', verbose_name='checkaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='beneficiary_name',
            field=models.CharField(default=1, help_text='nome do favorecido', max_length=50, verbose_name='favorecido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='operation',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='operção'),
        ),
    ]
