# Generated by Django 4.2.1 on 2023-06-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_privilegesaccount_mail_privilegesaccount_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilegesaccount',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='privilegesaccount',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='privilegesaccount',
            name='randomKey',
        ),
    ]
