# Generated by Django 4.2.1 on 2023-06-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_privilegesaccount_updated_at_privilegesaccount_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegesaccount',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='address_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=50, null=True, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='exist_deleted',
            field=models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
