# Generated by Django 4.2.1 on 2023-06-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_privilegesaccount_active_privilegesaccount_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegesaccount',
            name='exist_bank',
            field=models.BooleanField(default=False, help_text='Se for True o item granted para . Se for False o item foi denied.', verbose_name='Bancário -approved/rejected'),
        ),
    ]
