# Generated by Django 4.2.1 on 2023-06-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_privilegesaccount_exist_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegesaccount',
            name='exist_Pix',
            field=models.BooleanField(default=False, help_text='Conceber privilégios: ° Atividade PIX a esta conta.', verbose_name='PIX -approved/rejected'),
        ),
        migrations.AlterField(
            model_name='privilegesaccount',
            name='exist_bank',
            field=models.BooleanField(default=False, help_text='Conceber privilégios: ° Atividadea esta conta. ', verbose_name='Bancário -approved/rejected'),
        ),
    ]
