# Generated by Django 4.2.1 on 2023-06-01 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_privilegesaccount_exist_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegesaccount',
            name='exist_dinheiro',
            field=models.BooleanField(default=False, help_text='Conceber privilégios: ° Atividade em dinheiro a esta conta.', verbose_name='Dinheiro -approved/rejected'),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='paymentdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data'),
        ),
    ]
