# Generated by Django 4.2.1 on 2023-06-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_privilegesaccount_exist_dinheiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegesaccount',
            name='agenci',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='conta'),
        ),
    ]
