# Generated by Django 4.2.1 on 2023-06-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_privilegesaccount_agenci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilegesaccount',
            name='agenci',
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='branch',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='agencia'),
        ),
    ]
