# Generated by Django 4.2.1 on 2023-06-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_remove_privilegesaccount_agenci_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privilegesaccount',
            options={'ordering': ('bank',), 'verbose_name': 'paymentmethod', 'verbose_name_plural': 'meios de pagamentos'},
        ),
    ]
