# Generated by Django 4.2.1 on 2023-06-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_privilegesaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privilegesaccount',
            options={},
        ),
    ]
