# Generated by Django 4.2.1 on 2023-06-01 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0021_alter_privilegesaccount_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkaccounts', to='finance.ca', verbose_name='checkaccount')),
            ],
            options={
                'verbose_name': 'id',
                'verbose_name_plural': 'id',
                'ordering': ('pk',),
            },
        ),
        migrations.RemoveField(
            model_name='privilegesaccount',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='privilegesaccount',
            name='id',
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='checkaccount_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.checkaccount'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BalanceInitilAccount',
            fields=[
                ('checkaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.checkaccount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('movement_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data')),
                ('value_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.checkaccount', models.Model),
        ),
    ]
