# Generated by Django 4.2.1 on 2023-06-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_checkaccount_remove_privilegesaccount_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilegesaccount',
            name='name',
        ),
    ]
