# Generated by Django 4.2.1 on 2023-06-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_remove_privilegesaccount_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkaccount',
            options={'ordering': ('pk',), 'verbose_name': 'ida', 'verbose_name_plural': 'ida'},
        ),
    ]
