# Generated by Django 4.2.1 on 2023-06-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_checkaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkaccount',
            options={},
        ),
    ]
