# Generated by Django 4.2.1 on 2023-06-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_alter_privilegesaccount_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceinitilaccount',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='criado em'),
        ),
    ]
