# Generated by Django 4.2.1 on 2023-06-03 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_imposto_i_estadual_imposto_i_federal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceinitilaccount',
            name='movement_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 3), null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='imposto',
            name='movement_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 3), null=True, verbose_name='data'),
        ),
    ]
