# Generated by Django 4.2.1 on 2023-06-03 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_alter_balanceinitilaccount_movement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceinitilaccount',
            name='movement_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='imposto',
            name='movement_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data'),
        ),
    ]
