# Generated by Django 4.2.1 on 2023-07-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_alter_balanceinitilaccount_movement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceinitilaccount',
            name='situacao',
            field=models.CharField(blank=True, choices=[('criado', 'criado'), ('Analise', 'Analise'), ('Avaliado', 'Avaliado'), ('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imposto',
            name='situacao',
            field=models.CharField(blank=True, choices=[('criado', 'criado'), ('Analise', 'Analise'), ('Avaliado', 'Avaliado'), ('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privilegesaccount',
            name='situacao',
            field=models.CharField(blank=True, choices=[('criado', 'criado'), ('Analise', 'Analise'), ('Avaliado', 'Avaliado'), ('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], max_length=20, null=True),
        ),
    ]
