# Generated by Django 4.2.1 on 2023-07-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_balanceinitilaccount_situacao_imposto_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceinitilaccount',
            name='active',
            field=models.BooleanField(default=False, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='balanceinitilaccount',
            name='situacao',
            field=models.CharField(blank=True, choices=[('Aguardando', 'Aguardando'), ('Analise', 'Analise'), ('Avaliado', 'Avaliado'), ('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], default='Aguardando', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imposto',
            name='active',
            field=models.BooleanField(default=False, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='imposto',
            name='situacao',
            field=models.CharField(blank=True, choices=[('Aguardando', 'Aguardando'), ('Analise', 'Analise'), ('Avaliado', 'Avaliado'), ('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], default='Aguardando', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='privilegesaccount',
            name='active',
            field=models.BooleanField(default=False, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='privilegesaccount',
            name='situacao',
            field=models.CharField(blank=True, choices=[('Aguardando', 'Aguardando'), ('Analise', 'Analise'), ('Avaliado', 'Avaliado'), ('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], default='Aguardando', max_length=20, null=True),
        ),
    ]
