# Generated by Django 4.2.1 on 2023-07-30 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0034_alter_balanceinitilaccount_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceinitilaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='privilegio'),
        ),
        migrations.AlterField(
            model_name='balanceinitilaccount',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Analise'), ('4', 'Avaliado'), ('5', 'Pendente'), ('6', 'Negado')], default=2, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imposto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='privilegio'),
        ),
        migrations.AlterField(
            model_name='imposto',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Analise'), ('4', 'Avaliado'), ('5', 'Pendente'), ('6', 'Negado')], default=2, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='privilegesaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='privilegio'),
        ),
        migrations.AlterField(
            model_name='privilegesaccount',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Analise'), ('4', 'Avaliado'), ('5', 'Pendente'), ('6', 'Negado')], default=2, max_length=20, null=True),
        ),
    ]
