# Generated by Django 4.2.1 on 2023-08-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_delete_convert_name_base_create'),
        ('finance', '0036_alter_balanceinitilaccount_situacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ca',
            options={'ordering': ('name',), 'verbose_name': 'Criar conta para caixa', 'verbose_name_plural': 'Criar contas de caixas'},
        ),
        migrations.AlterModelOptions(
            name='imposto',
            options={'ordering': ('pk',), 'verbose_name': 'Criar um imposto', 'verbose_name_plural': 'Criar impostos'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ('name',), 'verbose_name': 'Criar meio de pagamento', 'verbose_name_plural': 'Criar meios de pagamentos'},
        ),
        migrations.AlterField(
            model_name='imposto',
            name='MovimentoConfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MovimentoConfig', to='crm.movimentoconfig', verbose_name='atender ao interesse'),
        ),
        migrations.AlterField(
            model_name='imposto',
            name='n_imposto',
            field=models.CharField(blank=True, help_text='Digite o nome do imposto', max_length=20, null=True, verbose_name='nome'),
        ),
    ]
