# Generated by Django 4.2.1 on 2023-08-28 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0043_alter_callexpenseeleutero1vagao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallApiQualificationGrandezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(blank=True, help_text='Entre com o valor coletado', null=True, verbose_name='valor')),
                ('matx_name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(null=True)),
                ('fk_grandeza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_fk_grandeza', to='app.grandeza', verbose_name='Undade_medida')),
            ],
            options={
                'verbose_name': 'grandeza',
                'verbose_name_plural': 'grandezas',
                'ordering': ('matx_name',),
            },
        ),
    ]
