# Generated by Django 4.2.1 on 2023-08-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_photo_fk_matrix'),
        ('api', '0004_callapiqualification_grandezas_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callapiqualification_grandezas_person',
            name='fk_Person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='un_fk_pessoa', to='crm.person', verbose_name='pessoa'),
            preserve_default=False,
        ),
    ]
