# Generated by Django 4.2.1 on 2023-08-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_callapiqualification_grandezas_person_fk_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='callapiqualificationgrandezas',
            name='fk_qualify_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='un_fk_qualificador_pessoa', to='api.callapiqualification_grandezas_person', verbose_name='qualificar pessoa'),
            preserve_default=False,
        ),
    ]
