# Generated by Django 4.2.1 on 2023-08-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_marketingcreate_classify_market_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingaddsuppliers',
            name='active',
        ),
        migrations.RemoveField(
            model_name='marketingaddsuppliers',
            name='created',
        ),
        migrations.RemoveField(
            model_name='marketingaddsuppliers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='marketingaddsuppliers',
            name='exist_deleted',
        ),
        migrations.RemoveField(
            model_name='marketingaddsuppliers',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='marketingaddsuppliers',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='marketingaddsuppliers',
            name='updated_at',
        ),
    ]
