# Generated by Django 4.2.1 on 2023-08-17 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0009_alter_payment_methods_options'),
        ('marketing', '0004_alter_marketingaddsuppliers_marketcreate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingaddsuppliers',
            options={'ordering': ('supplier_market',), 'verbose_name': 'mercado_map', 'verbose_name_plural': 'marketingaddsuppliers'},
        ),
        migrations.RemoveField(
            model_name='marketingaddsuppliers',
            name='marketcreate',
        ),
        migrations.AddField(
            model_name='marketingaddsuppliers',
            name='active',
            field=models.BooleanField(default=False, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='marketingaddsuppliers',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='criado em'),
        ),
        migrations.AddField(
            model_name='marketingaddsuppliers',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='privilegio'),
        ),
        migrations.AddField(
            model_name='marketingaddsuppliers',
            name='exist_deleted',
            field=models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado'),
        ),
        migrations.AddField(
            model_name='marketingaddsuppliers',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='marketingaddsuppliers',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Avaliando'), ('4', 'Analise'), ('5', 'Paralizado'), ('6', 'Pendente'), ('7', 'Negado')], default=2, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marketingaddsuppliers',
            name='supplier_market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='crm.photo', verbose_name='ramo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketingaddsuppliers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
