# Generated by Django 4.2.1 on 2023-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_marketingaddsuppliers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingaddsuppliers',
            name='supplier_market',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='classificação de operação'),
        ),
    ]
