# Generated by Django 4.2.1 on 2023-08-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacionChip', '0018_persona_exist_address'),
        ('expense', '0003_alter_spending_options'),
        ('marketing', '0006_alter_marketingaddsuppliers_supplier_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingaddsuppliers',
            name='supplier_market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mineralandiafornecedor', to='relacionChip.mineralandiafornecedor', verbose_name='mineslandia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketingcreate',
            name='spending_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spending', to='expense.spending', verbose_name='priory fornec.'),
        ),
    ]
