# Generated by Django 4.2.1 on 2023-08-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_alter_marketingaddsuppliers_supplier_market_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingAddSuppliers',
        ),
    ]
