# Generated by Django 4.2.1 on 2023-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=9, verbose_name='region')),
                ('description', models.CharField(max_length=150, verbose_name='desc')),
                ('progress', models.CharField(choices=[('texting', 'Texting'), ('creating', 'Creating'), ('doing', 'Doing'), ('done', 'Done')], max_length=8)),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'reginales',
                'ordering': ('region',),
            },
        ),
    ]
