# Generated by Django 4.2.1 on 2023-08-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviacao', models.CharField(max_length=150, verbose_name='abreviação')),
                ('distancia', models.CharField(max_length=9, verbose_name='unidade')),
                ('description', models.CharField(max_length=150, verbose_name='detalhe')),
                ('progress', models.CharField(choices=[('texting', 'Texting'), ('creating', 'Creating'), ('doing', 'Doing'), ('done', 'Done')], max_length=8)),
            ],
            options={
                'verbose_name': 'distancia',
                'verbose_name_plural': 'Distancias',
                'ordering': ('pk',),
            },
        ),
    ]
