# Generated by Django 4.2.1 on 2023-08-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_distancias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancias',
            options={'ordering': ('description', 'pk'), 'verbose_name': 'distancia', 'verbose_name_plural': 'Distancias'},
        ),
        migrations.AlterField(
            model_name='distancias',
            name='description',
            field=models.CharField(max_length=150, verbose_name='uso p.:'),
        ),
        migrations.AlterField(
            model_name='distancias',
            name='progress',
            field=models.CharField(blank=True, choices=[('1', 'Distâncias'), ('2', 'Time crono'), ('3', 'criar...')], max_length=8, null=True, verbose_name='Grupo App_indice'),
        ),
    ]
