# Generated by Django 4.2.1 on 2023-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_distancias_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancias',
            options={'ordering': ('progress', 'index', 'pk'), 'verbose_name': 'distancia', 'verbose_name_plural': 'Distancias'},
        ),
        migrations.AddField(
            model_name='distancias',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='indíce'),
        ),
    ]
