# Generated by Django 4.2.1 on 2023-08-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_distancias_options_distancias_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_name_Cobination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('abreviacao', models.CharField(max_length=150, verbose_name='abreviação')),
                ('name', models.CharField(max_length=9, verbose_name='nome/unidade...')),
                ('description', models.CharField(max_length=150, verbose_name='uso p.:')),
            ],
            options={
                'verbose_name': 'base de nomes para cobinatorio crm Fl1',
                'verbose_name_plural': 'bases de nomes para cobinatorio crm Fl1',
                'ordering': ('index', 'pk'),
            },
        ),
        migrations.DeleteModel(
            name='Distancias',
        ),
    ]
