# Generated by Django 4.2.1 on 2023-08-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_base_name_cobination_delete_distancias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_name_cobination',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome/unidade...'),
        ),
    ]
