# Generated by Django 4.2.1 on 2023-08-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_base_name_cobination_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_name_cobination',
            options={'ordering': ('progress', 'index', 'pk'), 'verbose_name': 'base de nomes para cobinatorio crm Fl1', 'verbose_name_plural': 'bases de nomes para cobinatorio crm Fl1'},
        ),
        migrations.AddField(
            model_name='base_name_cobination',
            name='progress',
            field=models.CharField(blank=True, choices=[('1', 'Distâncias'), ('2', 'Time crono'), ('3', 'criar...')], max_length=8, null=True, verbose_name='Grupo App_indice'),
        ),
    ]
