# Generated by Django 4.2.1 on 2023-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_base_name_cobination_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_name_cobination',
            name='abreviacao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='abreviação'),
        ),
        migrations.AlterField(
            model_name='base_name_cobination',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='uso p.:'),
        ),
        migrations.AlterField(
            model_name='base_name_cobination',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nome/unidade...'),
        ),
    ]
