# Generated by Django 4.2.1 on 2023-08-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_base_name_cobination_abreviacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_name_cobination',
            name='fase_principal',
            field=models.BooleanField(default=False, help_text='Marque se. Esta é uma referência principal de grandeza.', verbose_name='fase/principal'),
        ),
        migrations.AlterField(
            model_name='base_name_cobination',
            name='progress',
            field=models.CharField(blank=True, choices=[('1', 'Distâncias'), ('2', 'Liquidos'), ('3', 'Peso'), ('4', 'tempo')], max_length=8, null=True, verbose_name='Grupo App_indice'),
        ),
    ]
