# Generated by Django 4.2.1 on 2023-08-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_base_name_cobination_fase_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='nome/unidade...')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='uso p.:')),
            ],
            options={
                'verbose_name': 'grupo para App_indice',
                'verbose_name_plural': 'grupos para App_indice',
                'ordering': ('index', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='base_name_cobination',
            options={'ordering': ('index', 'pk'), 'verbose_name': 'base de nomes para cobinatorio crm Fl1', 'verbose_name_plural': 'bases de nomes para cobinatorio crm Fl1'},
        ),
        migrations.RemoveField(
            model_name='base_name_cobination',
            name='progress',
        ),
        migrations.CreateModel(
            name='base_name_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('abreviacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='abreviação')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='nome/unidade...')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='uso p.:')),
                ('fase_principal', models.BooleanField(default=False, help_text='Marque se. Esta é uma referência principal de grandeza.', verbose_name='fase/principal')),
                ('base_nome_grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indice_base_name', to='app.base_name', verbose_name='indice de grupos')),
            ],
            options={
                'verbose_name': 'base de nomes para cobinatorio crm Fl1',
                'verbose_name_plural': 'bases de nomes para cobinatorio crm Fl1',
                'ordering': ('base_nome_grup', 'index', 'pk'),
            },
        ),
    ]
