# Generated by Django 4.2.1 on 2023-08-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_base_name_alter_base_name_cobination_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_name_create',
            options={'ordering': ('base_nome_grup', 'index', 'pk'), 'verbose_name': 'base de nomes para cobinatorio crm created', 'verbose_name_plural': 'bases de nomes para cobinatorio crm created Fl1'},
        ),
    ]
