# Generated by Django 4.2.1 on 2023-08-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_delete_cobine_convert_app'),
        ('app', '0011_alter_base_name_create_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='base_name_Cobination',
        ),
    ]
