# Generated by Django 4.2.1 on 2023-08-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_base_name_cobination'),
    ]

    operations = [
        migrations.CreateModel(
            name='convert_Name_Base_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('function_name', models.CharField(blank=True, help_text='Caso tenha. Digite o valor de referencia para operação da função.', max_length=50, null=True, verbose_name='valor ref.')),
                ('vl_apresentado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valor_1', to='app.base_name', verbose_name='apresentado')),
                ('vl_observado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valor_2', to='app.base_name', verbose_name='apresentado')),
            ],
            options={
                'verbose_name': 'conversor de unidade',
                'verbose_name_plural': 'conversores de unidades',
                'ordering': ('index', 'pk'),
            },
        ),
    ]
