# Generated by Django 4.2.1 on 2023-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_convert_name_base_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convert_name_base_create',
            options={'ordering': ('vl_apresentado', 'index', 'pk'), 'verbose_name': 'conversor de unidade', 'verbose_name_plural': 'conversores de unidades'},
        ),
        migrations.AddField(
            model_name='convert_name_base_create',
            name='value_ref_int',
            field=models.IntegerField(blank=True, help_text='Caso tenha. Digite o valor de referencia para operação da função.', null=True, verbose_name='valor ref.'),
        ),
        migrations.AlterField(
            model_name='convert_name_base_create',
            name='function_name',
            field=models.CharField(blank=True, help_text='Caso tenha. Digite o codyname_espec_functions.', max_length=50, null=True, verbose_name='nome de função '),
        ),
    ]
