# Generated by Django 4.2.1 on 2023-08-21 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_convert_name_base_create_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert_name_base_create',
            name='vl_apresentado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_name1', to='app.base_name', verbose_name='apresentado'),
        ),
        migrations.AlterField(
            model_name='convert_name_base_create',
            name='vl_observado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_name2', to='app.base_name', verbose_name='apresentado'),
        ),
        migrations.CreateModel(
            name='name_base_Convert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('function_name', models.CharField(blank=True, help_text='Caso tenha. Digite o codyname_espec_functions.', max_length=50, null=True, verbose_name='nome de função ')),
                ('value_ref_int', models.IntegerField(blank=True, help_text='Caso tenha. Digite o valor de referencia para operação da função.', null=True, verbose_name='valor ref.')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_name_lock', to='app.base_name', verbose_name='combine')),
                ('vl_apresentado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_base', to='app.base_name', verbose_name='apresentado')),
            ],
            options={
                'verbose_name': 'conversor de unidade',
                'verbose_name_plural': 'conversores de unidades',
                'ordering': ('vl_apresentado', 'index', 'pk'),
            },
        ),
    ]
