# Generated by Django 4.2.1 on 2023-08-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_name_base_convert_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name_base_convert',
            options={'ordering': ('name', 'index', 'pk'), 'verbose_name': 'duple de unidade', 'verbose_name_plural': 'duple de unidades'},
        ),
        migrations.RenameField(
            model_name='name_base_convert',
            old_name='vl_apresentado',
            new_name='name',
        ),
    ]
