# Generated by Django 4.2.1 on 2023-08-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_name_base_convert_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_name',
            options={'ordering': ('index', 'name'), 'verbose_name': 'A) Criar indice', 'verbose_name_plural': 'A) Criar indices'},
        ),
        migrations.AlterModelOptions(
            name='base_name_create',
            options={'ordering': ('base_nome_grup', 'index', 'pk'), 'verbose_name': 'B) Criar Sub Titulo', 'verbose_name_plural': 'B) Criar Sub Titulos'},
        ),
        migrations.AlterModelOptions(
            name='name_base_convert',
            options={'ordering': ('name', 'index', 'pk'), 'verbose_name': 'C) Criar cobinação', 'verbose_name_plural': 'C) Criar cobinações'},
        ),
    ]
