# Generated by Django 4.2.1 on 2023-08-21 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_base_name_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='basenameConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('abreviacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='abreviação')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='nome/unidade...')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='uso p.:')),
                ('function_name', models.CharField(blank=True, help_text='Caso tenha. Digite o codyname_espec_functions.', max_length=50, null=True, verbose_name='nome de função ')),
                ('value_ref_int', models.IntegerField(blank=True, help_text='Caso tenha. Digite o valor de referencia para operação da função.', null=True, verbose_name='valor ref.')),
                ('fase_principal', models.BooleanField(default=False, help_text='Marque se. Esta é uma referência principal de grandeza.', verbose_name='fase/principal')),
                ('base_nome_grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indice_name', to='app.base_name', verbose_name='indice de grupos')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_name_base', to='app.base_name', verbose_name='apresentado')),
            ],
            options={
                'verbose_name': 'D) Criar Sub Cobination',
                'verbose_name_plural': 'D) Criar Sub Cobinations',
                'ordering': ('base_nome_grup', 'index', 'pk'),
            },
        ),
    ]
