# Generated by Django 4.2.1 on 2023-08-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_basenameconvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenameconvert',
            name='function_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nome de função '),
        ),
        migrations.AlterField(
            model_name='basenameconvert',
            name='value_ref_int',
            field=models.IntegerField(blank=True, null=True, verbose_name='valor ref.'),
        ),
    ]
