# Generated by Django 4.2.1 on 2023-08-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_basenameconvert_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenameconvert',
            name='base_nome_grup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indice_name', to='app.base_name', verbose_name='indice de grupos'),
        ),
    ]
