# Generated by Django 4.2.1 on 2023-08-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_base_name_create_base_nome_grup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name_base_convert',
            options={'ordering': ('index', 'pk'), 'verbose_name': 'C) Criar cobinação', 'verbose_name_plural': 'C) Criar cobinações'},
        ),
        migrations.RemoveField(
            model_name='name_base_convert',
            name='name',
        ),
        migrations.AddField(
            model_name='name_base_convert',
            name='name',
            field=models.ManyToManyField(null=True, related_name='name_base1', to='app.base_name_create', verbose_name='apresentado'),
        ),
    ]
