# Generated by Django 4.2.1 on 2023-08-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_name_base_convert_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_base_convert',
            name='function_name',
            field=models.CharField(default=1, help_text='Caso tenha. Digite o codyname_espec_functions.', max_length=50, verbose_name='nome de função '),
            preserve_default=False,
        ),
    ]
