# Generated by Django 4.2.1 on 2023-08-21 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_name_base_convert_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name_base_convert',
            options={'ordering': ('base_nome_grup', 'function_name', 'index', 'pk'), 'verbose_name': 'C) Criar cobinação', 'verbose_name_plural': 'C) Criar cobinações'},
        ),
        migrations.AddField(
            model_name='name_base_convert',
            name='base_nome_grup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indice_grup', to='app.base_name', verbose_name='indice'),
        ),
    ]
