# Generated by Django 4.2.1 on 2023-08-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_name_base_convert_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='convert_Name_Base_Create',
        ),
    ]
