# Generated by Django 4.2.1 on 2023-08-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_delete_convert_name_base_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='grandeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='nome/unidade...')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='uso p.:')),
            ],
            options={
                'verbose_name': 'A) Criar grandeza',
                'verbose_name_plural': 'A) Criar grandeza',
                'ordering': ('index', 'name'),
            },
        ),
    ]
