# Generated by Django 4.2.1 on 2023-08-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_grandeza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grandeza',
            options={'ordering': ('index', 'name'), 'verbose_name': 'Criar grandeza', 'verbose_name_plural': 'Criar grandezas'},
        ),
        migrations.AlterField(
            model_name='grandeza',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='uso p'),
        ),
        migrations.AlterField(
            model_name='grandeza',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='nome/unidade'),
        ),
    ]
