# Generated by Django 4.2.1 on 2023-08-23 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_base_name_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualificar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('abreviacao', models.CharField(max_length=150, verbose_name='abreviação')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='nome/unidade...')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='uso p.:')),
                ('fase_principal', models.BooleanField(default=False, help_text='Marque se. Esta é uma referência principal de grandeza.', verbose_name='principal/fase')),
                ('fk_grandeza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grandeza_fk', to='app.grandeza', verbose_name='qualificar grandeza')),
            ],
            options={
                'verbose_name': 'qualificador',
                'verbose_name_plural': 'qualificador de grandezas',
                'ordering': ('fk_grandeza', 'index', 'pk'),
            },
        ),
    ]
