# Generated by Django 4.2.1 on 2023-08-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_qualificar'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandeza',
            name='fk_matrix',
            field=models.BooleanField(default=True, help_text='habiliter this process.', verbose_name='conectar a matrix'),
        ),
        migrations.AddField(
            model_name='grandeza',
            name='matrix_evolution',
            field=models.CharField(default='matrix to call grandeza', max_length=255, verbose_name='Objeto'),
            preserve_default=False,
        ),
    ]
