# Generated by Django 4.2.1 on 2023-08-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_grandeza_fk_matrix_grandeza_matrix_evolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallMyMother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.IntegerField(unique=True, verbose_name='call')),
                ('fk_matrix', models.BooleanField(default=True, help_text='Activated this process.', verbose_name='Conect at matrix')),
                ('matrix_evolution', models.CharField(max_length=255, verbose_name='Object')),
            ],
            options={
                'verbose_name': 'evolution',
                'verbose_name_plural': 'Matrix',
                'ordering': ('call', 'fk_matrix', 'matrix_evolution'),
            },
        ),
        migrations.RemoveField(
            model_name='grandeza',
            name='fk_matrix',
        ),
        migrations.RemoveField(
            model_name='grandeza',
            name='matrix_evolution',
        ),
    ]
