# Generated by Django 4.2.1 on 2023-08-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_callmymother_remove_grandeza_fk_matrix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callmymother',
            options={'ordering': ('call', 'fk_matrix', 'matrix_evolution'), 'verbose_name': 'evolution', 'verbose_name_plural': '|__[Matrix]²£__|'},
        ),
        migrations.AlterField(
            model_name='callmymother',
            name='call',
            field=models.IntegerField(blank=True, null=True, verbose_name='call'),
        ),
    ]
