# Generated by Django 4.2.1 on 2023-08-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_qualificar_id_qualificar_callmymother_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='fk_matrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_matrix_regional', to='app.callmymother', verbose_name='Entre com uma regional'),
        ),
    ]
