# Generated by Django 4.2.1 on 2023-08-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_callexpenseeleutero1vagao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callexpenseeleutero1vagao',
            options={'ordering': ('call', 'fk_matrix', 'matrix_evolution'), 'verbose_name': 'evolution', 'verbose_name_plural': '|__[Matrix]²£_vg 1/_|'},
        ),
    ]
