# Generated by Django 4.2.1 on 2023-06-27 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='created_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='nome')),
                ('type_item', models.CharField(max_length=100, verbose_name='tipo')),
                ('progress', models.CharField(choices=[('texting', 'Texting'), ('creating', 'Creating'), ('doing', 'Doing'), ('done', 'Done')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'create_at_itens',
                'verbose_name_plural': 'create_my_itens',
                'ordering': ('sub_matrix_id',),
            },
        ),
        migrations.CreateModel(
            name='mtb_Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matx_name', models.CharField(max_length=255, verbose_name='nome')),
                ('progress', models.CharField(choices=[('texting', 'Texting'), ('creating', 'Creating'), ('doing', 'Doing'), ('done', 'Done')], max_length=8)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)screate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'matrix',
                'verbose_name_plural': 'matrices',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='mtb_Sublist_matri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_list_name', models.CharField(max_length=100, verbose_name='tipo')),
                ('progress', models.CharField(choices=[('texting', 'Texting'), ('creating', 'Creating'), ('doing', 'Doing'), ('done', 'Done')], max_length=8)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to='lockwell.mtb_matrix', verbose_name='categoria')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)screate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sub_matrix',
                'verbose_name_plural': 'create sub matrices',
                'ordering': ('catergory', 'sub_list_name'),
            },
        ),
        migrations.CreateModel(
            name='relacionaSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressRel', models.CharField(blank=True, choices=[('texting', 'Texting'), ('creating', 'Creating'), ('doing', 'Doing'), ('done', 'Done')], max_length=8, null=True)),
                ('createdrel_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedrel_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_matrices', to='lockwell.mtb_matrix', verbose_name='categoria')),
                ('createdrel_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)screate', to=settings.AUTH_USER_MODEL)),
                ('prod_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to='lockwell.created_items', verbose_name='produto lista')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtb_Sublist_matri', to='lockwell.mtb_sublist_matri', verbose_name='sub categoria')),
            ],
        ),
        migrations.AddField(
            model_name='created_items',
            name='sub_matrix_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_relate', to='lockwell.mtb_sublist_matri', verbose_name='create sub matrices'),
        ),
    ]
