# Generated by Django 4.2.1 on 2023-08-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockwell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtb_matrix',
            name='progress',
        ),
    ]
