# Generated by Django 4.2.1 on 2023-08-18 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('expense', '0008_alter_customizingspend_options'),
        ('lockwell', '0002_remove_mtb_matrix_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtb_matrix',
            options={'ordering': ('matx_name', 'evento_permitido'), 'verbose_name': 'matrix', 'verbose_name_plural': 'matrices'},
        ),
        migrations.AddField(
            model_name='mtb_matrix',
            name='active',
            field=models.BooleanField(default=False, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='mtb_matrix',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='criado em'),
        ),
        migrations.AddField(
            model_name='mtb_matrix',
            name='evento_permitido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='expense.customizingspend', verbose_name='Movimento configurado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtb_matrix',
            name='exist_deleted',
            field=models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado'),
        ),
        migrations.AddField(
            model_name='mtb_matrix',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Acessível para grup'),
        ),
        migrations.AddField(
            model_name='mtb_matrix',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
        migrations.AddField(
            model_name='mtb_matrix',
            name='movement_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='mtb_matrix',
            name='situacao',
            field=models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Avaliando'), ('4', 'Analise'), ('5', 'Paralizado'), ('6', 'Pendente'), ('7', 'Negado')], default=2, max_length=20, null=True),
        ),
    ]
