# Generated by Django 4.2.1 on 2023-06-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizingspend',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='criado em'),
        ),
    ]
