# Generated by Django 4.2.1 on 2023-08-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_customizingspend_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ('name',), 'verbose_name': 'despesas', 'verbose_name_plural': 'despesas'},
        ),
    ]
