# Generated by Django 4.2.1 on 2023-08-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_movimentoconfig_options'),
        ('expense', '0003_alter_spending_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='movement_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_expense', to='crm.movimentoconfig', verbose_name='Movimento configurado'),
        ),
    ]
