# Generated by Django 4.2.1 on 2023-08-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_spending_movement_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ('movement_expense',), 'verbose_name': 'despesas', 'verbose_name_plural': 'despesas'},
        ),
    ]
