# Generated by Django 4.2.1 on 2023-08-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_spending_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizingspend',
            options={'ordering': ('created_by', 'spending_classify'), 'verbose_name': 'item', 'verbose_name_plural': 'personalização das despesas'},
        ),
    ]
