# Generated by Django 4.2.1 on 2023-08-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('expense', '0006_alter_customizingspend_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizingspend',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Acessível para grup'),
        ),
        migrations.AddField(
            model_name='spending',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Acessível para grup'),
        ),
    ]
