# Generated by Django 4.2.1 on 2023-08-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_customizingspend_grup_spending_grup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizingspend',
            options={'ordering': ('created_by', 'grup', 'spending_classify'), 'verbose_name': 'item', 'verbose_name_plural': 'personalização das despesas'},
        ),
    ]
