# Generated by Django 4.2.1 on 2023-08-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_delete_convert_name_base_create'),
        ('expense', '0008_alter_customizingspend_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ('movement_expense',), 'verbose_name': 'Criar tratamento de despesa', 'verbose_name_plural': 'Criar tratamentos para despesas'},
        ),
        migrations.AlterField(
            model_name='spending',
            name='description',
            field=models.TextField(max_length=255, verbose_name='resumo em 200* caracteres'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='movement_expense',
            field=models.ForeignKey(help_text='Selecione a despesa para receber o tratamento', on_delete=django.db.models.deletion.CASCADE, related_name='movement_expense', to='crm.movimentoconfig', verbose_name='Criar uma despesa em:'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='name',
            field=models.CharField(help_text='Digite o nome para qualificar o tratamento da despesa criado', max_length=100, verbose_name='nome'),
        ),
    ]
