# Generated by Django 4.2.1 on 2023-08-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_callexpenseeleutero1vagao'),
        ('expense', '0009_alter_spending_options_alter_spending_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='fk_matrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_matrix_spending', to='app.callexpenseeleutero1vagao', verbose_name='Modularizado em call Expensend...vg1'),
        ),
    ]
