# Generated by Django 4.2.1 on 2023-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('UF', 'Estado'), ('MG', 'Minas Gerais'), ('SP', 'São paulo'), ('RJ', 'Rio de Janeiros'), ('ES', 'Espirito Santo')], max_length=2, null=True, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='address_city',
        ),
    ]
