# Generated by Django 4.2.1 on 2023-07-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_city_delete_address_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='distrito')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.city', verbose_name='cidade')),
            ],
            options={
                'verbose_name': 'bairro',
                'verbose_name_plural': 'bairros',
                'ordering': ('name',),
            },
        ),
    ]
