# Generated by Django 4.2.1 on 2023-07-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_district'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='district',
            new_name='distr',
        ),
    ]
