# Generated by Django 4.2.1 on 2023-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_rename_district_distr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, verbose_name='distrito')),
                ('endereco', models.CharField(max_length=40, verbose_name='distrito')),
                ('cidade', models.CharField(max_length=40, verbose_name='distrito')),
                ('Bairro', models.CharField(max_length=40, verbose_name='distrito')),
                ('uf', models.CharField(max_length=40, verbose_name='distrito')),
            ],
            options={
                'verbose_name': 'cep',
                'verbose_name_plural': 'cep_s',
                'ordering': ('uf',),
            },
        ),
    ]
