# Generated by Django 4.2.1 on 2023-07-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_cep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cep',
            old_name='Bairro',
            new_name='bairro',
        ),
    ]
