# Generated by Django 4.2.1 on 2023-07-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_rename_bairro_cep_bairro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cep',
            options={'ordering': ('uf',), 'verbose_name': 'cep', 'verbose_name_plural': 'ceps'},
        ),
        migrations.RenameField(
            model_name='cep',
            old_name='bairro',
            new_name='Bairro',
        ),
    ]
