# Generated by Django 4.2.1 on 2023-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_cep_options_rename_bairro_cep_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cep',
            name='Bairro',
        ),
        migrations.AlterField(
            model_name='cep',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='cep',
            name='cidade',
            field=models.CharField(max_length=40, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='cep',
            name='endereco',
            field=models.CharField(max_length=40, verbose_name='logradouro'),
        ),
        migrations.AlterField(
            model_name='cep',
            name='uf',
            field=models.CharField(max_length=40, verbose_name='uf'),
        ),
        migrations.AddField(
            model_name='cep',
            name='bairro',
            field=models.CharField(default=1, max_length=40, verbose_name='bairro'),
            preserve_default=False,
        ),
    ]
