# Generated by Django 4.2.1 on 2023-07-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_remove_cep_bairro_alter_cep_cep_alter_cep_cidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cep',
            options={'ordering': ('cep',), 'verbose_name': 'cep', 'verbose_name_plural': 'ceps'},
        ),
    ]
