# Generated by Django 4.2.1 on 2023-07-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_cep_fk_tb_auto_vincu_cep_tb_cep_vinculado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cep',
            name='fk_tb_auto_vincu',
        ),
        migrations.RemoveField(
            model_name='cep',
            name='tb_cep_vinculado',
        ),
    ]
