# Generated by Django 4.2.1 on 2023-07-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_remove_cep_fk_tb_auto_vincu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinCep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_cep_vinculado', models.CharField(blank=True, max_length=11, null=True, verbose_name='auto_')),
                ('fk_tb_auto_vincu', models.CharField(blank=True, max_length=9, null=True, verbose_name='fk_ resistro_vinculado')),
                ('cep', models.CharField(max_length=9, verbose_name='cep')),
                ('endereco', models.CharField(max_length=40, verbose_name='logradouro')),
                ('cidade', models.CharField(max_length=40, verbose_name='cidade')),
                ('bairro', models.CharField(max_length=40, verbose_name='bairro')),
                ('uf', models.CharField(max_length=40, verbose_name='uf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vinCep',
                'verbose_name_plural': 'C_ viculados',
                'ordering': ('cep',),
            },
        ),
    ]
