# Generated by Django 4.2.1 on 2023-07-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_vincep'),
    ]

    operations = [
        migrations.AddField(
            model_name='vincep',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento'),
        ),
    ]
