# Generated by Django 4.2.1 on 2023-08-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_vincep_complement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cep',
            options={'ordering': ('cep',), 'verbose_name': '@) base de dados e endereços', 'verbose_name_plural': '@) base de dados endereços'},
        ),
    ]
