# Generated by Django 4.2.1 on 2023-07-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_person_situacao_alter_person_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
    ]
