# Generated by Django 4.2.1 on 2023-07-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_person_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=False, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='situacao',
            field=models.CharField(blank=True, choices=[('Aguardando', 'Aguardando'), ('Analise', 'Analise'), ('Avaliado', 'Avaliado'), ('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], default='Aguardando', max_length=20, null=True),
        ),
    ]
