# Generated by Django 4.2.1 on 2023-08-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_person_situacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_methods',
            options={'ordering': ('pk',), 'verbose_name': 'finace.', 'verbose_name_plural': 'finaces!x ? crm.'},
        ),
    ]
