# Generated by Django 4.2.1 on 2023-08-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_payment_methods_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentoconfig',
            options={'ordering': ('routine',), 'verbose_name': 'Movimento_conf.', 'verbose_name_plural': 'Movimentos_conf.'},
        ),
    ]
