# Generated by Django 4.2.1 on 2023-08-18 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0013_alter_routine_options_movimentoconfig_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Acessível para grup'),
        ),
        migrations.AddField(
            model_name='person',
            name='movement_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data'),
        ),
    ]
