# Generated by Django 4.2.1 on 2023-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_person_grup_person_movement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='canal_vendas',
            field=models.CharField(blank=True, choices=[('Telefone', 'Telefone'), ('E-mail', 'E-mail'), ('Whatsapp', 'Whatsapp'), ('Presencial', 'Presencial'), ('Outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cargo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='interesses',
            field=models.TextField(blank=True, null=True, verbose_name='Intersses / Informes'),
        ),
        migrations.AddField(
            model_name='person',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='rede_social',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
