# Generated by Django 4.2.1 on 2023-08-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_person_canal_vendas_person_cargo_person_interesses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='referenciais',
            field=models.TextField(blank=True, null=True, verbose_name='Referncia / assuntos'),
        ),
    ]
