# Generated by Django 4.2.1 on 2023-08-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_person_referenciais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name', 'cargo'), 'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
    ]
