# Generated by Django 4.2.1 on 2023-08-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='Digite somente o primeiro nome.', max_length=50, verbose_name='nome pro'),
        ),
    ]
