# Generated by Django 4.2.1 on 2023-08-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_base_name_alter_base_name_cobination_options_and_more'),
        ('crm', '0018_alter_person_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobine_convert_App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('apresentador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valor_1', to='app.base_name_cobination', verbose_name='apresentado')),
            ],
            options={
                'verbose_name': 'apresentado',
                'verbose_name_plural': 'apresentador',
                'ordering': ('index', 'pk'),
            },
        ),
    ]
