# Generated by Django 4.2.1 on 2023-08-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_remove_movimentoconfig_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cobine_convert_App',
        ),
    ]
