# Generated by Django 4.2.1 on 2023-08-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_convert_name_base_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='convert_Name_Base_Create',
        ),
    ]
