# Generated by Django 4.2.1 on 2023-08-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_callmymother_remove_grandeza_fk_matrix_and_more'),
        ('crm', '0023_delete_convert_name_base_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('callmymother_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.callmymother')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='indíce')),
                ('unidade', models.CharField(max_length=70, verbose_name='nome/unidade')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='uso p')),
            ],
            options={
                'verbose_name': 'Criar grandeza',
                'verbose_name_plural': 'Criar grandezas',
                'ordering': ('index', 'unidade'),
            },
            bases=('app.callmymother',),
        ),
    ]
