# Generated by Django 4.2.1 on 2023-08-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_regions_fk_matrix'),
        ('crm', '0024_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='fk_matrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_matrix_fotos', to='app.callmymother', verbose_name='Entre com fotos'),
        ),
    ]
