# Generated by Django 4.2.1 on 2023-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0004_remove_step_1_created_remove_step_1_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step_1',
            name='movement_date',
        ),
        migrations.AddField(
            model_name='step_1',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='criado em'),
        ),
        migrations.AddField(
            model_name='step_1',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado em'),
        ),
    ]
