# Generated by Django 4.2.1 on 2023-08-19 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eleutero', '0006_step_1_movement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Avaliando'), ('4', 'Analise'), ('5', 'Paralizado'), ('6', 'Pendente'), ('7', 'Negado')], default=2, max_length=20, null=True)),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('movement_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data/hora')),
                ('step_number', models.IntegerField(blank=True, null=True, verbose_name='passo')),
                ('item_name', models.CharField(max_length=100, verbose_name='nome')),
                ('type_item', models.CharField(max_length=100, verbose_name='tipo')),
                ('progress', models.CharField(choices=[('1', 'Esperando'), ('2', 'Atrasado'), ('3', 'problema'), ('4', 'Preparando')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='privilegio')),
                ('grup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Acessível para grup')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to='eleutero.step_1', verbose_name='tarf')),
            ],
            options={
                'verbose_name': 'items',
                'verbose_name_plural': 'create_my_itens',
                'ordering': ('step', 'step_number'),
            },
        ),
    ]
