# Generated by Django 4.2.1 on 2023-08-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0007_step_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step_2',
            name='active',
        ),
        migrations.RemoveField(
            model_name='step_2',
            name='created',
        ),
        migrations.RemoveField(
            model_name='step_2',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='step_2',
            name='exist_deleted',
        ),
        migrations.RemoveField(
            model_name='step_2',
            name='grup',
        ),
        migrations.RemoveField(
            model_name='step_2',
            name='id',
        ),
        migrations.RemoveField(
            model_name='step_2',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='step_2',
            name='movement_date',
        ),
        migrations.RemoveField(
            model_name='step_2',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='step_2',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='step_2',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evento_fl1', to='eleutero.fl1', verbose_name='configurado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step_2',
            name='fl1_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eleutero.fl1'),
            preserve_default=False,
        ),
    ]
