# Generated by Django 4.2.1 on 2023-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0008_remove_step_2_active_remove_step_2_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step_2',
            name='evento',
        ),
        migrations.AddField(
            model_name='step_2',
            name='evento',
            field=models.ManyToManyField(related_name='evento_fl1', to='eleutero.fl1', verbose_name='configurado'),
        ),
    ]
