# Generated by Django 4.2.1 on 2023-08-19 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0005_remove_step_1_movement_date_step_1_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_1',
            name='movement_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data/hora'),
        ),
    ]
