# Generated by Django 4.2.1 on 2023-08-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0009_remove_step_2_evento_step_2_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step_2',
            name='evento',
        ),
    ]
