# Generated by Django 4.2.1 on 2023-08-22 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_delete_convert_name_base_create'),
        ('crm', '0023_delete_convert_name_base_create'),
        ('expense', '0009_alter_spending_options_alter_spending_description_and_more'),
        ('finance', '0037_alter_ca_options_alter_imposto_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0014_alter_cep_options'),
        ('eleutero', '0010_remove_step_2_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctrlSolo_Gr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Avaliando'), ('4', 'Analise'), ('5', 'Paralizado'), ('6', 'Pendente'), ('7', 'Negado')], default=2, max_length=20, null=True)),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('movement_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='nº')),
                ('matrix_evolution', models.CharField(max_length=255, verbose_name='Objeto')),
                ('description', models.TextField(help_text='Resuma em 300* caracteres.', verbose_name='descreva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='privilegio')),
                ('created_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)screate', to=settings.AUTH_USER_MODEL)),
                ('fk_base_name', models.ForeignKey(help_text='Para Registros de grandezas na base em sistema @admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_app', to='app.base_name', verbose_name='Registro de unidades')),
                ('fk_ca', models.ForeignKey(help_text='Para Registros de contas de caixa ... @admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ca', to='finance.ca', verbose_name='Registro de contas')),
                ('fk_cep', models.ForeignKey(help_text='Para Registros de endereços na base do sistema @admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cep', to='address.cep', verbose_name='Registro de endereços')),
                ('fk_imposto', models.ForeignKey(help_text='Para Registros de impostos em contas de caixa ... @admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_imposto', to='finance.imposto', verbose_name='Registro de impostos')),
                ('fk_paymentmethod', models.ForeignKey(help_text='Para Registros de tipos propriedades de pagamentos contas de caixa (dinheiro, cartão ...).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_paymentmethod', to='finance.paymentmethod', verbose_name='Registro de prop. pagamentos')),
                ('fk_person', models.ForeignKey(help_text='Para Registros de pessoas e profissionais em base em sistema ...', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_app', to='crm.person', verbose_name='Registro de pessoas')),
                ('fk_photo', models.ForeignKey(help_text='Para Registros de imagens na base em ...', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_photo', to='crm.photo', verbose_name='Registro de imagens')),
                ('fk_spending', models.ForeignKey(help_text='Para Registros de despesas e tratamentos em ... @admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_spending', to='expense.spending', verbose_name='Registro de despesas')),
                ('grup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Acessível para grup')),
            ],
            options={
                'verbose_name': 'Criar objeto',
                'verbose_name_plural': 'Criar objetos',
                'ordering': ('index', 'matrix_evolution'),
            },
        ),
    ]
