# Generated by Django 4.2.1 on 2023-08-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0011_ctrlsolo_gr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctrlsolo_gr',
            name='fk_cep',
        ),
        migrations.AlterField(
            model_name='ctrlsolo_gr',
            name='active',
            field=models.BooleanField(default=False, help_text='Para habiliter neste processo.', verbose_name='criar a enderços'),
        ),
    ]
