# Generated by Django 4.2.1 on 2023-08-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_grandeza'),
        ('eleutero', '0012_remove_ctrlsolo_gr_fk_cep_alter_ctrlsolo_gr_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctrlsolo_gr',
            name='fk_base_name',
        ),
        migrations.AddField(
            model_name='ctrlsolo_gr',
            name='fk_grandeza',
            field=models.ForeignKey(help_text='Para Registros de grandezas na base em sistema @admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_grandeza', to='app.grandeza', verbose_name='Registro de unidades'),
        ),
    ]
