# Generated by Django 4.2.1 on 2023-08-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0014_ctrlsolo_gr_grande_alter_ctrlsolo_gr_fk_grandeza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctrlsolo_gr',
            options={'ordering': ('index', 'matrix_evolution'), 'verbose_name': 'Criar estudo', 'verbose_name_plural': 'Criar estudos'},
        ),
    ]
