# Generated by Django 4.2.1 on 2023-08-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_grandeza_options_alter_grandeza_description_and_more'),
        ('eleutero', '0015_alter_ctrlsolo_gr_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrlsolo_gr',
            name='fk_grandeza',
            field=models.ForeignKey(help_text='Para Registros de grandezas na base em sistema @admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_grandeza', to='app.grandeza', verbose_name='Registro de unidades'),
        ),
    ]
