# Generated by Django 4.2.1 on 2023-08-22 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_grandeza_unidade'),
        ('eleutero', '0016_alter_ctrlsolo_gr_fk_grandeza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctrlsolo_gr',
            options={'ordering': ('index', 'matrix_evolution'), 'verbose_name': 'Criar objeto', 'verbose_name_plural': 'Criar objetos'},
        ),
        migrations.RemoveField(
            model_name='ctrlsolo_gr',
            name='fk_grandeza',
        ),
        migrations.RemoveField(
            model_name='ctrlsolo_gr',
            name='grande',
        ),
        migrations.AddField(
            model_name='ctrlsolo_gr',
            name='fk_base_name',
            field=models.ForeignKey(help_text='Para Registros de grandezas na base em sistema @admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_app', to='app.base_name', verbose_name='Registro de unidades'),
        ),
        migrations.AddField(
            model_name='ctrlsolo_gr',
            name='fk_cep',
            field=models.BooleanField(default=False, help_text='Para habiliter neste processo.', verbose_name='criar a enderços'),
        ),
        migrations.AlterField(
            model_name='ctrlsolo_gr',
            name='active',
            field=models.BooleanField(default=False, verbose_name='ativo'),
        ),
    ]
