# Generated by Django 4.2.1 on 2023-08-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_qualificar'),
        ('eleutero', '0019_remove_ctrlsolo_gr_fk_base_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrlsolo_gr',
            name='fk_base_name',
            field=models.ForeignKey(help_text='Para Registros de grandezas na base em sistema @admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_app', to='app.base_name', verbose_name='Registro de unidades'),
        ),
    ]
