# Generated by Django 4.2.1 on 2023-08-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0020_ctrlsolo_gr_fk_base_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctrlsolo_gr',
            name='movement_date',
        ),
    ]
