# Generated by Django 4.2.1 on 2023-08-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0022_sendbigdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendbigdata',
            options={'ordering': ('index',), 'verbose_name': 'Criar objeto', 'verbose_name_plural': 'Criar objetos'},
        ),
        migrations.RemoveField(
            model_name='sendbigdata',
            name='fk_matrix',
        ),
        migrations.RemoveField(
            model_name='sendbigdata',
            name='matrix_evolution',
        ),
    ]
