# Generated by Django 4.2.1 on 2023-08-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0024_alter_sendbigdata_options_sendbigdata_fk_matrix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendbigdata',
            name='fk_matrix',
        ),
        migrations.RemoveField(
            model_name='sendbigdata',
            name='matrix_evolution',
        ),
    ]
