# Generated by Django 4.2.1 on 2023-08-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_callexpenseeleutero1vagao'),
        ('eleutero', '0025_remove_sendbigdata_fk_matrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_1',
            name='fk_matrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_matrix_eleutero', to='app.callexpenseeleutero1vagao', verbose_name='Modularizado em call Expe...Eleutero...vg1'),
        ),
    ]
