# Generated by Django 4.2.1 on 2023-09-02 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleutero', '0028_alter_gn_evento_permitido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gn',
            name='call',
            field=models.IntegerField(help_text='piso ..', verbose_name='call'),
        ),
        migrations.AlterField(
            model_name='gn',
            name='coluna',
            field=models.CharField(help_text='coluna ..', max_length=15, verbose_name='col.'),
        ),
        migrations.AlterField(
            model_name='gn',
            name='index',
            field=models.IntegerField(help_text='linha ..', verbose_name='index l.'),
        ),
        migrations.CreateModel(
            name='Gn_ceu_terra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Avaliando'), ('4', 'Analise'), ('5', 'Paralizado'), ('6', 'Pendente'), ('7', 'Negado')], default=2, max_length=20, null=True)),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('movement_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data')),
                ('index', models.IntegerField(help_text='linha ..', verbose_name='index l.')),
                ('coluna', models.CharField(help_text='coluna ..', max_length=15, verbose_name='col.')),
                ('call', models.IntegerField(help_text='piso ..', verbose_name='call')),
                ('txt_name', models.CharField(max_length=150, verbose_name='nome')),
                ('txt_referncial', models.CharField(max_length=15, verbose_name='ref./*')),
                ('mem_description', models.TextField(verbose_name='descreva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='privilegio')),
                ('created_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)screate', to=settings.AUTH_USER_MODEL)),
                ('evento_permitido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_eleutero_gn', to='eleutero.gn', verbose_name='Gênesis.conf.')),
                ('grup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Acessível para grup')),
            ],
            options={
                'verbose_name': 'A criação Céu Terra',
                'verbose_name_plural': 'Gênesis o princípio',
                'ordering': ('call', 'index', 'coluna'),
            },
        ),
    ]
