# Generated by Django 4.2.1 on 2023-09-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0031_alter_gn_ceu_terra_options_gn_luz'),
    ]

    operations = [
        migrations.AddField(
            model_name='gn_luz',
            name='evento_matrix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_GN', to='eleutero.gn', verbose_name='config_Gênesis..'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gn_luz',
            name='evento_permitido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fk_gn_in_eleutero', to='eleutero.gn_ceu_terra', verbose_name='conf.Gênesis.'),
        ),
    ]
