# Generated by Django 4.2.1 on 2023-09-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0032_gn_luz_evento_matrix_alter_gn_luz_evento_permitido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gn',
            options={'ordering': ('call', 'index', 'coluna', 'txt_referncial', 'txt_name'), 'verbose_name': 'Gênesis', 'verbose_name_plural': 'Gênesis'},
        ),
        migrations.AlterModelOptions(
            name='gn_ceu_terra',
            options={'ordering': ('coluna', 'index', 'call', 'txt_referncial', 'txt_name'), 'verbose_name': 'A criação Céu Terra', 'verbose_name_plural': 'Gênesis o princípio'},
        ),
        migrations.AlterModelOptions(
            name='gn_luz',
            options={'ordering': ('coluna', 'index', 'call', 'evento_permitido', 'txt_referncial', 'txt_name'), 'verbose_name': 'A luz', 'verbose_name_plural': 'Gênesis cap 1'},
        ),
    ]
