# Generated by Django 4.2.1 on 2023-09-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleutero', '0035_gn_registro_meterorologia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gn_ceu_terra',
            options={'ordering': ('coluna', 'index', 'call', 'txt_referncial', 'txt_name'), 'verbose_name': 'A criação Céu Terra', 'verbose_name_plural': 'Criar um Protocolo'},
        ),
        migrations.AlterModelOptions(
            name='gn_luz',
            options={'ordering': ('situacao', 'coluna', 'index', 'call', 'evento_permitido', 'txt_referncial', 'txt_name'), 'verbose_name': 'A luz', 'verbose_name_plural': 'Aplicar o protocolo'},
        ),
        migrations.AlterModelOptions(
            name='gn_noite',
            options={'ordering': ('inicio_date', 'fim_date', 'situacao', 'coluna', 'index', 'call', 'evento_permitido', 'txt_referncial', 'txt_name'), 'verbose_name': 'A Noite', 'verbose_name_plural': 'atividade de protocolo registrados horarios e detalhes'},
        ),
    ]
