# Generated by Django 4.2.1 on 2023-07-29 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rede_social', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Outro', 'Outro')], max_length=20, null=True)),
                ('canal_vendas', models.CharField(blank=True, choices=[('Telefone', 'Telefone'), ('E-mail', 'E-mail'), ('Whatsapp', 'Whatsapp'), ('Presencial', 'Presencial'), ('Outro', 'Outro')], max_length=20, null=True)),
                ('interesses', models.TextField(blank=True, max_length=100, null=True, verbose_name='Intersses / Informes')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='endereço')),
                ('address_number', models.IntegerField(blank=True, null=True, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('country', models.CharField(blank=True, default='Brasil', max_length=50, null=True, verbose_name='país')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('trade_name', models.CharField(max_length=200, verbose_name='Nome fantasia')),
                ('social_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome social')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Cnpj')),
                ('ie', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Ei')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ('trade_name',),
            },
        ),
    ]
