# Generated by Django 4.2.1 on 2023-07-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='interesses',
            field=models.TextField(blank=True, null=True, verbose_name='Intersses / Informes'),
        ),
    ]
