# Generated by Django 4.2.1 on 2023-08-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_alter_relchipsupplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('situacao', '-active', 'exist_deleted', 'trade_name'), 'verbose_name': 'fornecedor', 'verbose_name_plural': 'fornecedores'},
        ),
    ]
