# Generated by Django 4.2.1 on 2023-09-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0011_alter_supplier_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='meterorologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=10, verbose_name='referencia-1')),
                ('coleta', models.CharField(default='met.decea.mil.br', max_length=10, verbose_name='coleta da infor ')),
                ('tipodoc', models.CharField(max_length=5, verbose_name='tipo de documento ')),
                ('diadocsis', models.IntegerField(verbose_name='dia da coleta do sistema')),
                ('horadocsis', models.CharField(max_length=7, verbose_name='hora da coleta da previsão')),
                ('coletainfo1', models.CharField(max_length=10, verbose_name='coleta info 1')),
                ('coletainfo2', models.CharField(max_length=10, verbose_name='coleta info 2')),
                ('coletainfo3', models.CharField(max_length=10, verbose_name='coleta info 3')),
                ('coletainfo4', models.CharField(max_length=10, verbose_name='coleta info 4')),
                ('coletainfo5', models.CharField(max_length=10, verbose_name='coleta info 5')),
                ('coletainfo6', models.CharField(max_length=10, verbose_name='coleta info 6')),
                ('coletainfo7', models.CharField(max_length=10, verbose_name='coleta info 7')),
                ('coletainfo8', models.CharField(max_length=10, verbose_name='coleta info 8')),
                ('coletainfo9', models.CharField(max_length=10, verbose_name='coleta info 9')),
                ('coletainfo10', models.CharField(max_length=10, verbose_name='coleta info 10')),
                ('coletainfo11', models.CharField(max_length=10, verbose_name='coleta info 11')),
                ('coletainfo12', models.CharField(max_length=10, verbose_name='coleta info 12')),
                ('coletainfo13', models.CharField(max_length=10, verbose_name='coleta info 13')),
                ('coletainfo14', models.CharField(max_length=10, verbose_name='coleta info 14')),
            ],
            options={
                'verbose_name': 'meterorologia',
                'verbose_name_plural': 'meteorologicas',
                'ordering': ('-diadocsis', '-pk'),
            },
        ),
    ]
