# Generated by Django 4.2.1 on 2023-09-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0012_meterorologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterorologia',
            name='coleta',
            field=models.CharField(default='met.decea.mil.br', max_length=70, verbose_name='coleta da infor '),
        ),
    ]
