# Generated by Django 4.2.1 on 2023-09-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0013_alter_meterorologia_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterorologia',
            name='coleta',
            field=models.CharField(blank=True, default='met.decea.mil.br', max_length=70, null=True, verbose_name='coleta da infor '),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 1'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo10',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 10'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo11',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 11'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo12',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 12'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo13',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 13'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo14',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 14'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 2'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 3'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 4'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 5'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 6'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo7',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 7'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo8',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 8'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='coletainfo9',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 9'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='diadocsis',
            field=models.IntegerField(blank=True, null=True, verbose_name='dia da coleta do sistema'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='horadocsis',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='hora da coleta da previsão'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='referencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='referencia-1'),
        ),
        migrations.AlterField(
            model_name='meterorologia',
            name='tipodoc',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='tipo de documento '),
        ),
    ]
