# Generated by Django 4.2.1 on 2023-09-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0014_alter_meterorologia_coleta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Var_meteorologicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(blank=True, choices=[('1', 'Aprovado'), ('2', 'Aguardando'), ('3', 'Avaliando'), ('4', 'Analise'), ('5', 'Paralizado'), ('6', 'Pendente'), ('7', 'Negado')], default=2, max_length=20, null=True)),
                ('active', models.BooleanField(default=False, verbose_name='ativo')),
                ('exist_deleted', models.BooleanField(default=True, help_text='Se for True o item existe. Se for False o item foi deletado.', verbose_name='existe/deletado')),
                ('canal_vendas', models.CharField(blank=True, choices=[('1', 'BECMG'), ('2', 'FM')], max_length=20, null=True)),
                ('coletainfo1', models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 1')),
                ('coletainfo2', models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 2')),
                ('coletainfo3', models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 3')),
                ('coletainfo4', models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 4')),
                ('coletainfo5', models.CharField(blank=True, max_length=10, null=True, verbose_name='coleta info 5')),
                ('registro_meterorologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_met', to='supplier.meterorologia', verbose_name='Reg.met.')),
            ],
            options={
                'verbose_name': 'integre meterorologia',
                'verbose_name_plural': 'integração meteorologicas',
                'ordering': ('-coletainfo1', '-pk'),
            },
        ),
    ]
