# Generated by Django 4.2.1 on 2023-06-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsocial',
            name='Spending',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spending', to='expense.spending', verbose_name='spend'),
            preserve_default=False,
        ),
    ]
